server:
  port: 8082

spring:
  datasource:
    second:
      driverClassName: oracle.jdbc.driver.OracleDriver
      url: jdbc:oracle:thin:@192.168.3.113:1521:test
      username: medicine
      password: medicine
    primary:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://47.104.249.62:3306/changyuan?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true
      username: root
      password: admin
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1

  jta:
    transaction-manager-id: txManager

#mybatis:
#  mapper-locations: classpath*:/mapper/*Mapper.xml




